"""Compatibility facade for LNO327 superconducting pairing utilities.

New downstream analysis code should prefer ``lno327.api`` for the narrower
stable API. The package root keeps historical re-exports for existing scripts.
"""

from .bdg_response import (
    BdGEigensystem,
    BdGKernelComponents,
    BdGSuperconductingResponse,
    bdg_current_vertex,
    bdg_current_vertices,
    bdg_diamagnetic_kernel,
    bdg_diamagnetic_vertex,
    bdg_eigensystem,
    bdg_paramagnetic_kernel_imag_axis,
    bdg_superconducting_response_imag_axis,
    bdg_total_kernel_imag_axis,
)
from .finite_q_engine import (
    BdGPhaseCorrectionError,
    bdg_finite_q_response_imag_axis,
    collective_form_factor,
    collective_goldstone_counterterm,
    pairing_form_factor_matrix,
)
from .finite_q_primitives import (
    BdGFiniteQResponseComponents,
    bdg_finite_q_contact_vertex,
    bdg_finite_q_vector_vertex,
)
from .casimir import CasimirSetup, casimir_energy_integrand, casimir_torque_integrand
from .conductivity import (
    ConductivityEigensystem,
    ConductivityTensor,
    KuboConfig,
    anisotropy_delta,
    anisotropy_summary,
    bosonic_matsubara_energy_eV,
    conductivity_eigensystem,
    conductivity_matrix_diagnostics,
    fermi_function,
    k_weights,
    kubo_conductivity_imag_axis,
    kubo_conductivity_real_axis,
    rotate_conductivity,
    uniform_bz_mesh,
)
from .gap_analysis import (
    FermiSurfacePoints,
    GapStatistics,
    band_gap_projection,
    fermi_surface_points,
    gap_statistics_by_band,
    gap_statistics_on_fermi_surface,
)
from .models.lno327_four_orbital.normal import normal_state_hamiltonian
from .models.lno327_four_orbital.parameters import (
    NormalStateParameters,
    ORBITAL_BASIS,
    PairingAmplitudes,
    PairingKind,
)
from .models.lno327_four_orbital.vertices import (
    normal_state_mass_operator,
    normal_state_mass_operators,
    normal_state_velocity_operator,
    normal_state_velocity_operators,
)
from .models.lno327_four_orbital.bdg import bdg_hamiltonian
from .models.lno327_four_orbital.pairing import (
    dwave_pairing_matrix,
    pairing_matrix,
    spm_pairing_matrix,
)
from .response_interface import (
    LocalSheetResponse,
    ResponseKind,
    compare_local_responses_imag_axis,
    conductivity_tensor_from_matrix,
    local_response_imag_axis,
    matrix_symmetry_diagnostics,
    validate_local_response_symmetry,
)
from .response_conventions import (
    ResponseUnitConvention,
    SheetConductivityConvention,
    SheetConductivityConversion,
    model_response_to_sheet_conductivity,
    model_response_to_reflection_dimensionless,
    require_sheet_conductivity_for_reflection,
    sheet_conductivity_to_reflection_dimensionless,
    sheet_conductivity_to_dimensionless,
)
from .static_response import (
    StaticResponsePolicy,
    StaticResponseResult,
    local_response_matsubara_index,
)

__all__ = [
    "ORBITAL_BASIS",
    "BdGEigensystem",
    "BdGKernelComponents",
    "BdGFiniteQResponseComponents",
    "BdGPhaseCorrectionError",
    "BdGSuperconductingResponse",
    "CasimirSetup",
    "ConductivityEigensystem",
    "ConductivityTensor",
    "FermiSurfacePoints",
    "GapStatistics",
    "KuboConfig",
    "LocalSheetResponse",
    "NormalStateParameters",
    "PairingAmplitudes",
    "PairingKind",
    "ResponseKind",
    "ResponseUnitConvention",
    "SheetConductivityConvention",
    "SheetConductivityConversion",
    "StaticResponsePolicy",
    "StaticResponseResult",
    "anisotropy_delta",
    "anisotropy_summary",
    "bdg_current_vertex",
    "bdg_current_vertices",
    "bdg_diamagnetic_kernel",
    "bdg_diamagnetic_vertex",
    "bdg_eigensystem",
    "bdg_finite_q_contact_vertex",
    "bdg_finite_q_response_imag_axis",
    "bdg_finite_q_vector_vertex",
    "bdg_hamiltonian",
    "bdg_paramagnetic_kernel_imag_axis",
    "bdg_superconducting_response_imag_axis",
    "bdg_total_kernel_imag_axis",
    "bosonic_matsubara_energy_eV",
    "band_gap_projection",
    "casimir_energy_integrand",
    "casimir_torque_integrand",
    "conductivity_eigensystem",
    "collective_form_factor",
    "collective_goldstone_counterterm",
    "conductivity_matrix_diagnostics",
    "conductivity_tensor_from_matrix",
    "compare_local_responses_imag_axis",
    "dwave_pairing_matrix",
    "fermi_function",
    "fermi_surface_points",
    "gap_statistics_by_band",
    "gap_statistics_on_fermi_surface",
    "k_weights",
    "kubo_conductivity_imag_axis",
    "kubo_conductivity_real_axis",
    "local_response_imag_axis",
    "local_response_matsubara_index",
    "matrix_symmetry_diagnostics",
    "model_response_to_sheet_conductivity",
    "model_response_to_reflection_dimensionless",
    "normal_state_hamiltonian",
    "normal_state_mass_operator",
    "normal_state_mass_operators",
    "normal_state_velocity_operator",
    "normal_state_velocity_operators",
    "pairing_matrix",
    "pairing_form_factor_matrix",
    "rotate_conductivity",
    "spm_pairing_matrix",
    "require_sheet_conductivity_for_reflection",
    "sheet_conductivity_to_reflection_dimensionless",
    "sheet_conductivity_to_dimensionless",
    "uniform_bz_mesh",
    "validate_local_response_symmetry",
]
